### PR TITLE
Add "actually..." (☝️🤓) emoji cow

### PR DESCRIPTION
**Pull request by hasecilu**
Nice to see the project being maintained. I made this cow a few days ago, I even shared it on the Fediverse:  https://lemm.ee/post/39579433

It's based on the _popular_ "erm actually" ☝️🤓 emoji combo, someone may like it so here we are.

I was thinking maybe it's better to rename the file to `actually.cow`, the bad ortography comes from a meme, maybe not so relevant here, what do you think?

### CODE REVIEW

**Comment by apjanke** [comment]
Cool! Thanks for the contribution. Sorry for taking so long to reply here. Day job and family stuff and all that.

> I was thinking maybe it's better to rename the file to actually.cow, the bad ortography comes from a meme, maybe not so relevant here, what do you think?

Yeah, I think `actually.cow` would be better. The bad orthography is funny, but (at least for me) it's hard to type. Getting out the command `cowsay -f ackchyually -b "Blah blah blah blah"` took me a little thinking and work. In some cases, you can do tab completion, so just `cowsay -f ack<TAB>` and that's fine, but that depends on third-party bash or zsh completion definitions that aren't part of Cowsay itself, and not all users will have those available. So I'd prefer to go with `actually.cow` here.

I'm going to cut a new cowsay 3.8.4 release in a couple days here, and it'll pick your cow up if it's merged by then.

### Contributor stuff

Would you like your name added to the new [`CONTRIBUTORS.md`](https://github.com/cowsay-org/cowsay/blob/main/CONTRIBUTORS.md) file? I merged it to `main` just now. If you'd like, add an entry for yourself to the Contributors section as part of this PR, rebasing your PR's branch on `main` to make the file visible to you.

Also, would you mind dual-licensing your contribution here under GPL 3.0 "or later" and Artistic License 1.0, for maximum compatibility with the rest of the cowsay code? I'm trying to clear up the licensing situation (see [here](https://github.com/cowsay-org/cowsay/commit/dfc1c28681bb05790cd799f970bf691b2430579a) on the dev/free-mime branch) and it looks like that's what we need for full consistency. But I haven't gotten that documented on the `main` branch yet so it still just says "GPL 3.0". We don't have a formal licensing document yet; just replying with a comment here saying you grant that license should be fine. Sorry for the hassle.

**Comment by hasecilu** [comment]
Hi, change done. Regarding the dual licensing I AGREE.

**Comment by apjanke** [comment]
Merged. Thanks for the cow!

**Comment by apjanke** [comment]
Cowsay [3.8.4](https://github.com/cowsay-org/cowsay/releases/tag/v3.8.4) is out with your "actually" cow!

**Comment by hasecilu** [comment]
Nice! :cow:

**Pull request merged**
