### PR TITLE
Add alpaca.cow

### PR DESCRIPTION
**Pull request by Inf166**
I like cows.
But I like alpacas even more.

If you agree, let's merge!

### CODE REVIEW

**Comment by apjanke** [comment]
Heck yeah alpacas!

I dunno if I *agree* with you per se: I do like alpacas. But I also like cows. And I'm not sure if I like alpacas *more* than cows. Like, alpacas are kinda shaped cooler, and have a funner-sounding name. And alpaca wool clothes are generally more interesting, practical, and humane than cow leather. But on the other hand, if you get in to an argument with a cow, they will trample you and kill you, and your life is over. But if you get in to an argument with an alpaca, they will seriously bray and spit at you. And then you have to live with that shit for the rest of your life. Have you ever seen the size of loogie a llama or alpaca can hawk up and spit at you? Catch one of those in the face and that experience will stay with you for decades.

Are you familiar with Tenacious Unicorn Ranch? It's a queer anarchist alpaca ranch up in Colorado. I'm a fan of theirs.

* https://www.tenacious-unicorn-ranch.com/
* https://en.wikipedia.org/wiki/Tenacious_Unicorn_Ranch

Anyway, yes, let's get an alpaca up in `cowsay` here!

## Art

I'm generally liking how this looks, while trying this PR out here:

```text
[cowsay] $ git status
On branch inf166-master
Your branch is up to date with 'inf166/master'.

nothing to commit, working tree clean
[cowsay] $ git remote -v | grep inf
inf166	https://github.com/Inf166/cli-tool-alpacasay (fetch)
inf166	https://github.com/Inf166/cli-tool-alpacasay (push)
[cowsay] $
[cowsay] $
[cowsay] $ ./cowsay -f alpaca "I am a cute travel-size llama!"
 ________________________________
< I am a cute travel-size llama! >
 --------------------------------
          \   ‘^----^‘
           \ (◕(‘人‘)◕)
              (  8    )        ô
              (    8  )_______( )
              ( 8      8        )
              (_________________)
                ||          ||
               (||         (||
[cowsay] $
```

Is this "alpaca" ASCII art something you produced yourself, or did you find it somewhere else on the internet or something?

And what do you think about the little `(` parentheses for the alpaca's feet here? Maybe they're a little big? Is there something like an "upside-down P" or line art glyph we could use here instead to make them a bit daintier? Not that alpacas' feet need to be *dainty* per se, but the feet in this particular drawing are reading as just a bit too big to me.

I like his nose and face art here.

## Logistics and Testing

I thnk I like the cow art in this PR, but there are a couple logisitical issues with this PR.

First, please rebase and squash your commits. I think a new cowfile should show up as a single commit; no need for your work-in-progress checkpoints to be preserved as multiple commits.

Reference:

View in GitHub web page:

image

View in Sourcetree Git client on macOS:

image

I'd rather see this as one "Add alpaca.cow" commit, with no separate "align head" or "rename" commits. I think those are work-in-progress tasks, and have no value for posterity, so do not need to be preserved in the main git commit sequence here.

Also, since the rename has been done here (I think), I think the commit message should be "Add alpaca.cow", and not "Add alpaka.cow" (with a "k").

This cowsay repo does not use "[FEATURE]" or "[TASK]" etc prefixes in its commit messages, so you can drop those.

I'm having a bit of a hard time testing this PR. This PR is sourcing commits from the `master` branch on the [Inf166/cli-tool-alpacasay repo](https://github.com/Inf166/cli-tool-alpacasay). It's conventional/normal for you to make a separate branch on your forked repo, put changes there, and then make a PR from that branch. Making a PR from your `master` gets messy, especially if any new commits show up on `master` in the "parent" repo that you forked. (Which, if it's an active repo, they will.)

How about you make a new separate branch for this, and submit a new PR from there? If you're using a standard Git client, if you check out your master branch, and create a new branch from there, that new branch will include this new commit. And then you can push that new branch up to your GitHub fork repo. And then `git reset` the master branch on your fork, so you ca n then pull in new commits from upstream.

**Comment by apjanke** [comment]
Oh, BTW @Inf166 , on your https://github.com/Inf166/cli-tool-alpacasay fork repo's GitHub page, it shows this when I view it:

image

This here https://github.com/cowsay-org/cowsay repo is not itself "the classic cowsay project" by any means. This repo is my newfangled attempt at a (unauthorized/unblessed) *fork* of the classic Cowsay project, to get it on GitHub and "modernize" it a bit, particularly with regards to packaging and Linux distro support and some "semi-enterprise" shizz.

How about "Inf166's alpacafied fork of apjanke's fork of the classic cowsay project" for or something like that for the repo About text here?

**Comment by Inf166** [comment]
I got the Alpaca face from [here](https://www.fastemoji.com/(%E2%97%95(%E2%80%98%E4%BA%BA%E2%80%98)-%E2%97%95)-Meaning-Emoji-Emoticon-Alpaca-Ascii-Art-Animal-Horse-Llama-Japanese-Kaomoji-Smileys-21635.html
).
And the inspiration for the whole art from [here](https://www.redbubble.com/de/i/gru%C3%9Fkarte/ASCII-Alpaka-BW-von-Yincinerate/45126625.5MT14).

But I created the art myself.

Thank you for your advice. I will change my repo accordingly.
Any wishes for the branch name?

Regarding your questions about enhancing the art, I am no experienced ASCII artist by any means. I tried my best and worked with the ASCII Table found on the web. But if you know any glyphs I could have used instead, feel free to enhance them. But I could not find anything that worked for me.

**Comment by apjanke** [comment]
> I got the Alpaca face from [here](https://www.fastemoji.com/(%E2%97%95(%E2%80%98%E4%BA%BA%E2%80%98)-%E2%97%95)-Meaning-Emoji-Emoticon-Alpaca-Ascii-Art-Animal-Horse-Llama-Japanese-Kaomoji-Smileys-21635.html).
And the inspiration for the whole art from [here](https://www.redbubble.com/de/i/gru%C3%9Fkarte/ASCII-Alpaka-BW-von-Yincinerate/45126625.5MT14). [...] But I created the art myself.

Works for me!

If you would like to put your name in a "credits" file somewhere here, let me know. I'm not entirely sure how that works in this repo, but we can figure it out.

> Any wishes for the branch name?

Does not matter at all, as long as it is not "master" or "main".

> Regarding your questions about enhancing the art, I am no experienced ASCII artist by any means. I tried my best and worked with the ASCII Table found on the web. But if you know any glyphs I could have used instead, feel free to enhance them. But I could not find anything that worked for me.

I am not an experienced ASCII/Unicode artist either. I just know there's a lot of Unicode characters out there, and was thinking there's maybe something better.

I think it's probably best for cowsay's cows to stick with regular ASCII characters and not go exploring the deeper reaches of Unicode just yet. Simplicity and portability! I also looked through the main ASCII and Latin-1 tables myself, and I think you're right: "(" is actually the best available glyph to use here from these common/baseline character sets.

So, sorry for sending you on a bit of a wild goose chase here by just tossing off a "hmm, is there something better we could do here?" without really thinking about it or knowing what that better thing might be.

----

Anyway, I think your code is all good here. "Squash" your commits so we can have a tidy Git commit history, and we'll merge!

**Pull request closed without merging**
