### PR TITLE
Include fixes that are present in Debian and Fedora packages for cowsay

### PR DESCRIPTION
**Pull request by filbranden**
Also include a fox, which is present on Debian/Ubuntu but not yet on Fedora.

This includes two other fixes:
- Balloon is broken when message is empty.
- Balloon produces trailing spaces.

After including fixes carried by distros, we can lobby the distros to start using this version as a new upstream.

I plan to follow up with more of the fixes from the distros in follow up PRs.

### CODE REVIEW

**Comment by filbranden** [comment]
Ping @apjanke, please take a look.

**Comment by apjanke** [comment]
Hi! Thanks for the ping. I didn't have my Watch setting for this repository turned on.

Looks good to me. Let me review more closely after work tonight and I'll merge.

**Comment by apjanke** [comment]
Okay, good to go; you're merged.

Thanks for the contribution!

**Comment by filbranden** [comment]
Thank you! I'll probably have more contributions to make in the future. I'm going through the patches applied by Debian and Fedora and I'll propose changes here to match features (and possibly add tests) they have there. Cheers!

**Pull request merged**
