### PR TITLE
Added cupcake  

### PR DESCRIPTION
**Pull request by NuthanB**
Added cupcake with appropriate changes hope for a merge soon :)

### CODE REVIEW

**Comment by apjanke** [comment]
"Soon" is now. Merged!

Thanks for working with me on this, and humoring my requests for "clean" PRs.

This will go out in the next release of cowsay-ng.

**Comment by NuthanB** [comment]
Thank you much, made my day !!!

**Comment by NuthanB** [comment]
Re: Licensing Clarification for Cowsay Contribution

Hi Andrew Janke,

Thank you for reaching out regarding the licensing clarification for the
Cowsay-org fork.

I am willing to expand the license grant on my contribution to "GPL 1.0 or
later, or Artistic License 1.0" to align with the original Cowsay licensing
terms.

Please let me know if any further steps are needed from my side to
formalize this update.

Best regards,
Nuthan B

**Comment by apjanke** [comment]
Great, thanks Nuthan!

Nothing further needed from your side. I think your comment here serves as sufficient notice of the license expansion. I have recorded it in the repo's copyright info files in https://github.com/cowsay-org/cowsay/commit/b264d17fb721a92fb19c2e2ae16f1c31d18f828d.

**Pull request merged**
