### PR TITLE
Add cupcake to cowboy

### PR DESCRIPTION
**Pull request by NuthanB**
Hello  , I  would like to add this cupcake art cowboy-org , I had made it for a special person, would appreciate it being added to the repo.
Thank you so much!.

### CODE REVIEW

**Comment by apjanke** [comment]
Oh, that's a nice cupcake.

Your commit history is a little hinky here. [Squash this](https://gitbetter.substack.com/p/how-to-squash-git-commits) to a single commit, and you've got a merge.

image

**Comment by NuthanB** [comment]
Hey, sorry for the late response, I tried to Squash the above, but it's not working, worked a while with it and was not able to figure it out, could I fork it again and create a new pull request?

**Comment by apjanke** [comment]
> could I fork it again and create a new pull request?

Yep!

**Comment by apjanke** [comment]
Superseded by https://github.com/cowsay-org/cowsay/pull/36

**Pull request closed without merging**
