### PR TITLE
Add alpaca.cow

### PR DESCRIPTION
**Pull request by Inf166**
The second time is the charm!

```I like cows.
But I like alpacas even more.
If you agree, let's merge!
```
I got the Alpaca face from [here](https://www.fastemoji.com/(%E2%97%95(%E2%80%98%E4%BA%BA%E2%80%98)-%E2%97%95)-Meaning-Emoji-Emoticon-Alpaca-Ascii-Art-Animal-Horse-Llama-Japanese-Kaomoji-Smileys-21635.html).
And the inspiration for the whole art from [here](https://www.redbubble.com/de/i/gru%C3%9Fkarte/ASCII-Alpaka-BW-von-Yincinerate/45126625.5MT14).
But I created the art myself.

Thank you for your advice. I have changed my repo accordingly.

Regarding your questions about enhancing the art, I am no experienced ASCII artist by any means. I tried my best and worked with the ASCII Table found on the web. But if you know any glyphs I could have used instead, feel free to enhance them. But I could not find anything that worked for me.

### CODE REVIEW

**Comment by apjanke** [comment]
Yeah, that's what I'm talkin' about!

Please see https://github.com/cowsay-org/cowsay/pull/32#issuecomment-1305395095 for discussion on the old PR. This here PR addresses all the comments/questions I had there, so I'm just merging it here, and not gonna copy/paste all that commentary.

Thanks for your cow-ntribution, @Inf166!

**Comment by apjanke** [comment]
Hi, @mai-space ! I'm trying to [clarify and harmonize the licensing situation](https://github.com/cowsay-org/cowsay/issues/68) for Cowsay and this cowsay-org fork.

Would you be willing to expand the license grant on your contribution here to be "GPL 1.0 or later, or Artistic License 1.0", matching the original Cowsay licensing terms?

From 2019 to November 2024, this cowsay-org fork was labeled as being licensed under just GPL 3.0, not the broader original Cowsay terms. I think that means your contribution is implicitly licensed under GPL 3.0. An explicit grant of the broader "GPL 1.0+ or Artistic" licensing would ensure that the licensing for this file is compatible with the old school Cowsay licensing, and we can eventually unify and simplify the licensing for the whole package.

**Comment by mai-space** [comment]
I am all for unifying the community. I just could not contribute to the original repository.

This was really just a funny side project for having alpacas on my CLI.

If you want, you can update the license in a pull request and I will gladly support that initiative!

**Comment by apjanke** [comment]
Excellent!

Here's a PR to update the license grant documentation for your alpaca: https://github.com/cowsay-org/cowsay/pull/75. If you could drop a comment there approving this update or do an "Approve" PR review, I think that's all that's needed.

Thanks for being up for this.

**Pull request merged**
