### PR TITLE
Add among us crewmate cow

### PR DESCRIPTION
**Pull request by marekmaskarinec**
```
 ______
< lgtm >
 ------
   \
    \  .——————.
      .———.    \
     (     )   +——\
      `———´    |  |
      |        |  |
      |   __   +——/
      \__/  \__/
```

### CODE REVIEW

**Review by mvolfik — APPROVED** [review]
omg i need this

**Comment by ProkopRandacek** [comment]
this would save me a lot of time

**Review by chamik — APPROVED** [review]
truly a needed update

**Comment by apjanke** [comment]
Cute! Nice addition. Should be able to get this merged soon.

Typo in file name?

image

Should that be `amongus.cow` instead of `amogus.cow`? Or maybe just `sus.cow`? (Unless "sus" is considered offensive. I'm a little unclear on the state of that.) Or is "amogus" itself a joke? (I don't play Among Us.)

### Contributor stuff

Would you like your name added to the new `CONTRIBUTORS.md` file? I merged it to `main` just now. Rebase your PR's branch to pick it up and add an entry for yourself to the Contributors section if you'd like. (To do the rebase cleanly, you might need to move your work to a separate branch instead of main. Or maybe just `git pull --rebase upstream/main` will work; I'm not sure.)

Also, would you mind dual-licensing your contribution here under GPL 3.0 "or later" and Artistic License 1.0, for maximum compatibility with the rest of the cowsay code? I'm trying to clear up the licensing situation (see [here](https://github.com/cowsay-org/cowsay/commit/dfc1c28681bb05790cd799f970bf691b2430579a) on the dev/free-mime branch) and it looks like that's what we need for full consistency. But I haven't gotten that documented on the `main` branch yet so it still just says "GPL 3.0". We don't have a formal licensing document yet; just replying with a comment here saying you grant that license should be fine.

**Comment by marekmaskarinec** [comment]
As suggested, I have changed the file name to `sus.cow` and updated the CONTRIBUTORS.md files accordingly.

**Comment by apjanke** [comment]
That's a merge, then. Thanks!

I should be able to get this rolled out in a new 3.8.4 release within a couple days.

**Comment by apjanke** [comment]
Cowsay [3.8.4](https://github.com/cowsay-org/cowsay/releases/tag/v3.8.4) is out with your sus cow!

**Comment by kenos1** [comment]
this is a needed addition in my life

**Pull request merged**
