### PR TITLE
llama cow

### PR DESCRIPTION
**Pull request by con-f-use**
image

### CODE REVIEW

**Comment by apjanke** [comment]
Already pulled in https://github.com/cowsay-org/cowsay/commit/cc88e608a33ef326b386cc21bd3cdd89d1e7cb89, with your author credit. Thanks!

**Comment by apjanke** [comment]
Hi, @con-f-use! I'm trying to [clarify and harmonize the licensing situation](https://github.com/cowsay-org/cowsay/issues/68) for Cowsay and this cowsay-org fork.

Would you be willing to expand the license grant on your contribution here to be "GPL 1.0 or later, or Artistic License 1.0", matching the original Cowsay licensing terms?

From 2019 to November 2024, this cowsay-org fork was labeled as being licensed under just GPL 3.0, not the broader original Cowsay terms. I think that means your contribution is implicitly licensed under GPL 3.0 only. An explicit grant of the broader "GPL 1.0+ or Artistic" licensing would ensure that the licensing for this file is compatible with the old school Cowsay licensing, and we can eventually unify and simplify the licensing for the whole package.

**Comment by con-f-use** [comment]
> Would you be willing to expand the license grant on your contribution here to be "GPL 1.0 or later, or Artistic License 1.0", matching the original Cowsay licensing terms?

I would, you have my go-ahead.

**Comment by apjanke** [comment]
Excellent. Thanks!

Noted in https://github.com/cowsay-org/cowsay/commit/82f3ecbe4aae1900fef58566f2a31974fe3b8906.

**Pull request closed without merging**
