### PR TITLE
Avoid Trademark and Copyright Enforcement Action

### PR DESCRIPTION
**Pull request by bone-baboon**
To avoid trademark and copyright enforcement action it is probably a
good idea to remove the files in the Questionable Files section below.

# Character Trademark and Copyright

Fictional characters can be protected by copyright and trademark.
This is an explanation that uses Disney characters.
<https://info.legalzoom.com/article/legal-use-disney-characters> 

# Questionable Files

Some of the files used by cowsay's -f option appear to be questionable.  I looked at all the files in the /share/cows/ directory and the following files were the ones I identified as questionable. All of the following charters are likely trademarked and copyrighted (however I have not verified that).

* beavis.zen.cow 
  * <https://en.wikipedia.org/wiki/Beavis_and_Butt-Head>
  * Uses trademarked character name and character

* bud-frogs.cow 
  * <https://en.wikipedia.org/wiki/Budweiser>
  * <https://en.wikipedia.org/wiki/Budweiser_Frogs>
  * Uses trademark and characters

* cheese.cow 
  * <https://en.wikipedia.org/wiki/Milk_%26_Cheese>
  * Uses trademark character name and character

* ghostbusters.cow 
  * <https://en.wikipedia.org/wiki/Ghostbusters>
  * Uses trademark and no ghost logo

* hellokitty.cow 
  * <https://en.wikipedia.org/wiki/Hello_Kitty>
  * Uses trademark and character

* luke-koala.cow 
  * <https://en.wikipedia.org/wiki/Luke_Skywalker>
  * Uses trademarked character name

* milk.cow 
  * <https://en.wikipedia.org/wiki/Milk_%26_Cheese>
  * Uses trademark character name and character

* ren.cow 
  * <https://en.wikipedia.org/wiki/The_Ren_%26_Stimpy_Show>
  * Uses trademark character name and character

* stimpy.cow 
  * <https://en.wikipedia.org/wiki/The_Ren_%26_Stimpy_Show>
  * Uses trademark character name and character

* telebears.cow 
  * <https://brand.berkeley.edu/uncategorized/telebears/>
  * Uses trademark

* vader-koala.cow
  * <https://en.wikipedia.org/wiki/Darth_Vader>
  * Uses trademark character name

These two may be fair use:

* moofasa.cow 
  * <https://en.wikipedia.org/wiki/Mufasa#Mufasa>

* vader.cow 
  * <https://en.wikipedia.org/wiki/Darth_Vader>

### CODE REVIEW

**Comment by xuhdev** [comment]
Why is it an issue to use trademark names? Are users of cowsay confused by these names to mistakenly take cowsay as a work from Disney?

**Comment by bone-baboon** [comment]
@xuhdev

> Why is it an issue to use trademark names?

<https://en.wikipedia.org/wiki/Trademark#Usage> says "The owner of a
trademark may pursue legal action against trademark infringement.".

This could be a potential problem for authors and maintainers of
cowsay repositories that infringe on trademarks.

This could also be a potential problem for operating systems that
distribute cowsay.  There are many operating systems distributing cowsay. <https://repology.org/project/cowsay/versions>

Preventing legal action seems like a simpler thing to do than dealing
with legal action.

**Comment by xuhdev** [comment]
If someone "owns" a trademark means no one else can use that phrase, it would produce absurd results. Would you say "I drank a bottle of dark drinkable liquid with bubbles" instead of saying "I drank a bottle of Coke"? Can't a novelist or a journalist mention any trademarks in their writings? :)

Maybe you can wanna check out this: https://en.m.wikipedia.org/wiki/Trademark_infringement#Factors

If the chance of consumer confusion is remote, I don't see trademark infringement. Likewise, if I don't repeat the phrase but cause consumer confusion, I can be liable (Say I name my movie "Star War" instead of "Star Wars").

**Comment by bone-baboon** [comment]
<https://github.com/tnalpgge/rank-amateur-cowsay/pull/4> has relevant information for this pull request.

**Comment by apjanke** [comment]
Closing out this old conversation.

**Pull request closed without merging**
